#!/usr/bin/env python3
"""Fast docling server using DocumentConverter singleton.

A lightweight FastAPI server optimized for hybrid PDF processing:
1. Using a single DocumentConverter instance (no per-request initialization)
2. Returns only JSON (DoclingDocument format) - markdown/HTML generated by Java
3. Models load at startup, not on the first request, so the first conversion is
   no slower than later ones. On a cold model cache startup takes minutes; the
   log names the load and reports how long it took.

Usage:
    opendataloader-pdf-hybrid [--port PORT] [--host HOST] [--ocr-lang LANG]
                              [--force-ocr | --no-ocr] [--ocr-engine ENGINE] [--psm N]
                              [--device DEVICE]
                              [--enrich-formula] [--enrich-picture-description]
                              [--max-file-size MB]

    # Default: http://localhost:5002
    opendataloader-pdf-hybrid

    # Custom port
    opendataloader-pdf-hybrid --port 5003

    # Disable OCR when the PDF already has reliable embedded text (#387)
    opendataloader-pdf-hybrid --no-ocr

    # Use Tesseract for a language EasyOCR doesn't support (#439)
    opendataloader-pdf-hybrid --ocr-engine tesseract --ocr-lang mal

    # Chinese + English OCR with force full-page OCR
    opendataloader-pdf-hybrid --ocr-lang "ch_sim,en" --force-ocr

    # Korean OCR
    opendataloader-pdf-hybrid --ocr-lang "ko"

    # Explicitly use Apple Silicon GPU (MPS)
    opendataloader-pdf-hybrid --device mps

    # Force CPU-only processing
    opendataloader-pdf-hybrid --device cpu

    # More detail while diagnosing (adds thread and logger columns, docling internals)
    opendataloader-pdf-hybrid --log-level debug

    # With formula enrichment (LaTeX extraction)
    opendataloader-pdf-hybrid --enrich-formula

    # With picture description (alt text generation)
    opendataloader-pdf-hybrid --enrich-picture-description

    # Combined: OCR + enrichments
    opendataloader-pdf-hybrid --ocr-lang "en" --enrich-formula --enrich-picture-description

API Endpoints:
    GET  /health              - Health check
    POST /v1/convert/file     - Convert PDF to JSON

The /v1/convert/file endpoint parameters:
    - files: PDF file (multipart/form-data)
    - page_ranges: Page range to process (optional)

Requirements:
    Install with hybrid extra: pip install opendataloader-pdf[hybrid]
"""

import argparse
import asyncio
import contextvars
import logging
import logging.config
import os
import re
import secrets
import sys
import tempfile
import threading
import time
import traceback

# Enable docling per-step pipeline profiling (layout, ocr, table_structure, etc.)
# Must be set before docling settings singleton is instantiated.
os.environ.setdefault("DOCLING_DEBUG_PROFILE_PIPELINE_TIMINGS", "true")
from contextlib import asynccontextmanager
from typing import Any, Optional

# Correlates every log line emitted while serving one request. Python's logging
# has no equivalent of Java's MDC, so the id travels in a context variable and
# `_RequestIdFilter` copies it onto each record for the formatter to render.
_request_id: contextvars.ContextVar[str] = contextvars.ContextVar(
    "request_id", default="-"
)


class _RequestIdFilter(logging.Filter):
    """Stamp each record with the request being served when it was emitted.

    Reaches docling's lines too, since they are logged on the thread running
    the conversion. Records from a thread docling started itself, and those
    emitted outside any request, carry "-": a context variable is not
    inherited by a bare `threading.Thread`, so the id genuinely is not known
    there rather than being omitted.
    """

    def filter(self, record: logging.LogRecord) -> bool:
        record.request_id = _request_id.get()
        return True


# A single format for our logger, docling's and uvicorn's. Before this, our
# lines came from `basicConfig` while uvicorn kept its own timestamp-less
# `levelprefix` format, so the two could not be read as one timeline -- the
# reason the #414 report could not be diagnosed from the log alone.
_LOG_FORMAT = "%(asctime)s.%(msecs)03d | %(levelname)-7s | %(request_id)-12s | %(message)s"
_LOG_FORMAT_DEBUG = (
    "%(asctime)s.%(msecs)03d | %(levelname)-7s | %(request_id)-12s | "
    "%(threadName)-14s | %(name)s | %(message)s"
)
_LOG_DATEFMT = "%Y-%m-%d %H:%M:%S"

# Marks the handler `configure_logging` owns, so that repeat calls replace that
# one and leave an embedding application's handlers alone.
_CONSOLE_HANDLER = "odl_console"

# Ids only have to stay distinct among the requests visible together in a log.
# Three bytes collide at about 3% over a thousand requests, which is frequent
# enough to mislead someone correlating lines; six makes it negligible.
_REQUEST_ID_BYTES = 6


class _IndentTracebacks(logging.Formatter):
    """Formatter that keeps a traceback from looking like separate records.

    `exc_info` text is appended after the formatted message, and an exception
    raised over caller-supplied data carries that data in its message -- a
    parser error quoting PDF object bytes, for instance. A newline in there
    ends the physical line, and what follows can be shaped exactly like one of
    this module's own records, so a failed request could be made to read as a
    successful one.

    Each continuation line is prefixed so it cannot be mistaken for a record
    of its own. The traceback's own structure is left intact, since that is
    what makes it worth logging.
    """

    _CONTINUATION = "    | "

    def format(self, record: logging.LogRecord) -> str:
        # `logging.Formatter.format` caches the traceback it renders on the
        # record, and every later formatter reuses that text. A handler an
        # embedding application installed formats the same record first, so
        # the cache would hold an unprefixed traceback by the time this
        # formatter runs -- and the prefixing below would never happen.
        # Cleared so the prefix is applied to whatever this handler writes.
        cached, record.exc_text = record.exc_text, None
        try:
            return super().format(record)
        finally:
            # Put it back: the next handler is entitled to its own rendering,
            # and leaving None would make it re-render rather than reuse.
            record.exc_text = cached

    def formatException(self, ei: Any) -> str:
        text = super().formatException(ei)
        return "\n".join(self._CONTINUATION + line for line in text.splitlines())


def configure_logging(level: str = "info") -> None:
    """Point our logger, docling's and uvicorn's at one console handler.

    `--log-level` previously reached only `uvicorn.run()`, while this module
    pinned the root logger to INFO at import time, so the flag had no effect on
    our own or docling's output. Setting the levels here makes it real.

    docling shares our level so that its startup lines -- which model is being
    fetched, which OCR engine was chosen -- land in the same timeline as ours.
    Timing the load is this server's own job: docling times downloads, not the
    weight loading that dominates a warm cache.

    Built by hand rather than with `dictConfig`, which is destructive: a
    non-incremental config clears the root logger's handlers and calls
    `close()` on each one. Handlers belonging to an embedding application
    survived that only as objects -- a `FileHandler` reopened in "w" mode or a
    handler that latches on `close()` would stop recording. Only the handler
    this function owns is replaced.
    """
    level_name = level.upper()
    level_value = getattr(logging, level_name, logging.INFO)

    formatter = _IndentTracebacks(
        _LOG_FORMAT_DEBUG if level_name == "DEBUG" else _LOG_FORMAT,
        datefmt=_LOG_DATEFMT,
    )

    root = logging.getLogger()
    for handler in list(root.handlers):
        if getattr(handler, "name", None) == _CONSOLE_HANDLER:
            root.removeHandler(handler)
            handler.close()

    console = logging.StreamHandler(stream=sys.stdout)
    console.name = _CONSOLE_HANDLER
    console.setFormatter(formatter)
    console.addFilter(_RequestIdFilter())
    root.addHandler(console)
    root.setLevel(level_value)

    for name, logger_level in (
        ("docling", level_value),
        # httpx logs a line per HTTP request at INFO, which during a model
        # fetch means one per HuggingFace metadata call. The others are
        # DEBUG-only today; pinned so that a future default cannot start
        # narrating our startup.
        ("httpx", logging.WARNING),
        ("httpcore", logging.WARNING),
        ("urllib3", logging.WARNING),
        ("filelock", logging.WARNING),
        ("uvicorn", level_value),
        ("uvicorn.error", level_value),
        # Our own per-request lines carry the caller, file, size, page count
        # and timings, so uvicorn's access line would only repeat the request
        # without the id that ties it to the rest.
        ("uvicorn.access", logging.WARNING),
    ):
        logger_obj = logging.getLogger(name)
        logger_obj.setLevel(logger_level)
        # uvicorn sets `propagate = False` on its loggers when it configures
        # logging; cleared so its lines reach our console in our format. Its
        # handlers need no removal -- `main()` passes `log_config=None`, so it
        # installs none -- and removing them wholesale would have detached a
        # handler an embedding application had attached here.
        logger_obj.propagate = True


# Not called at import: `basicConfig` used to be a documented no-op once the
# root logger had handlers, so importing this module could not disturb an
# embedding application's logging. dictConfig has no such courtesy -- it would
# reset the root level -- so the server configures logging in `main()` instead.
logger = logging.getLogger(__name__)

# Configuration
DEFAULT_HOST = "0.0.0.0"
DEFAULT_PORT = 5002
MAX_FILE_SIZE = 0  # No file size limit by default (0 = unlimited)
UPLOAD_CHUNK_SIZE = 1024 * 1024  # 1MB chunks for streaming upload

# OCR engine kinds we filter out from `--ocr-engine` choices.
# `kserve_v2_ocr` requires a separate KServe v2 / Triton inference server, which
# is unsuitable for the local hybrid mode this server is designed for.
# Single source of truth shared by `create_converter`, `main()` argparse, and tests
# to avoid drift between production and test code.
_OCR_ENGINE_DENYLIST = frozenset({"kserve_v2_ocr"})


def _non_negative_int(value: str) -> int:
    """Argparse type validator that rejects negative integers."""
    parsed = int(value)
    if parsed < 0:
        raise argparse.ArgumentTypeError("--max-file-size must be >= 0")
    return parsed


# Global converter instance (initialized on startup with CLI options)
converter = None

# Serialize converter.convert() calls. The converter singleton was designed for
# sequential use; this lock keeps that guarantee while allowing the event loop
# to stay responsive via asyncio.to_thread().
_convert_lock = threading.Lock()

# Regex matching lone surrogates (U+D800..U+DFFF) and null characters
_INVALID_UNICODE_RE = re.compile(r"[\ud800-\udfff\x00]")


def _extract_failed_pages_from_errors(errors: list[str]) -> list[int]:
    """Extract failed page numbers from error messages.

    Docling error messages follow the pattern "Page N: <error>" (e.g.,
    "Page 26: std::bad_alloc") or, when no error description is available,
    a bare "Page N" with no colon. Even when docling includes failed pages
    in the pages dict as empty entries, the error messages reliably
    indicate which pages actually failed.

    Args:
        errors: List of error message strings.

    Returns:
        Sorted list of 1-indexed page numbers that failed.
    """
    failed = set()
    page_pattern = re.compile(r"^Page\s+(\d+)(?::|$)")
    for msg in errors:
        m = page_pattern.match(msg)
        if m:
            failed.add(int(m.group(1)))
    return sorted(failed)


def extract_timings(result: Any) -> dict[str, Any]:
    """Extract per-step pipeline timings from a Docling ConversionResult.

    Requires DOCLING_DEBUG_PROFILE_PIPELINE_TIMINGS=true (set at module level).
    Returns a dict keyed by step name (e.g. "layout", "ocr", "table_structure")
    with total_s, avg_s, and count for each step.
    """
    timings_out: dict[str, Any] = {}
    raw_timings = getattr(result, "timings", None)
    if not raw_timings:
        return timings_out
    unreadable: list[str] = []
    last_error: Exception | None = None
    for name, item in raw_timings.items():
        try:
            timings_out[name] = {
                "total_s": round(item.total(), 4),
                "avg_s": round(item.avg(), 4) if item.count > 0 else 0.0,
                "count": item.count,
            }
        except Exception as e:
            # Collected rather than logged here: a docling API change fails
            # every step, and one warning per step per request would bury the
            # lines someone is reading the log for.
            unreadable.append(name)
            last_error = e
    if unreadable:
        # Still said out loud once: silently dropping timings makes the
        # per-stage breakdown look absent instead of broken.
        logger.warning(
            "timings_unreadable %s",
            _pairs(
                failed=len(unreadable),
                total=len(raw_timings),
                steps=_bounded(",".join(unreadable)),
                error=_bounded(str(last_error), 500),
            ),
        )
    return timings_out


# The docling profiling keys worth a place on the completion line, mapped to
# shorter log keys. docling emits more than these -- layout_postprocess,
# reading_order, doc_assemble and others -- so the whitelist keeps the line
# short, and it also keeps a docling key from colliding with a fixed one:
# these are splatted as keyword arguments into `_pairs`, where a duplicate
# raises TypeError and costs the request its response.
_STAGE_LABELS = {
    "ocr": "ocr",
    "layout": "layout",
    "table_structure": "tables",
    "page_parse": "parse",
}

# Heartbeat spacing, widening as a conversion runs on: attentive while the
# operator is still deciding whether anything is wrong, sparse once the answer
# is "it is simply slow". A flat 15s spent 31 lines on an eight-minute
# conversion, which is 31 lines saying the same thing.
_PROGRESS_INTERVAL_S = 15.0
_PROGRESS_BACKOFF = (
    (60.0, 15.0),    # first minute: every 15s
    (300.0, 60.0),   # to five minutes: every minute
    (None, 120.0),   # beyond: every two minutes
)


# The two control characters worth reading back: a newline forges a new record
# and a carriage return overwrites the line already printed, so both are named
# rather than dropped. Every other non-printable becomes `_REPLACEMENT` -- an
# ANSI escape has no reading worth preserving.
_CONTROL_ESCAPES = {"\n": "\\n", "\r": "\\r"}

# Stands in for a character with no reading worth keeping. Deliberately ASCII:
# U+FFFD cannot be encoded on a cp949 or cp1252 console, and `logging` drops a
# record it cannot write -- so a filename holding one zero-width character
# would have erased its own log line on a Korean Windows console, turning this
# sanitizing into a way to go unlogged.
_REPLACEMENT = "?"


def _pairs(**fields: Any) -> str:
    """Render fields as logfmt, in the order given, skipping None.

    The lines this module emits are read two ways: by someone watching the
    console, and by grep or a log reader afterwards. logfmt serves both --
    `dur=34.5s` says what the number is without a legend, and `ocr=33.8s` can
    be extracted without a regex per line. A value holding a space or a quote
    is quoted, since an unquoted one would parse as two fields.
    """
    out = []
    for key, value in fields.items():
        if value is None:
            continue
        text = str(value)
        # Backslashes first, so that the escapes below are the only ones in
        # the output. Doubling afterwards would re-escape them, and `a\nb`
        # typed literally would render identically to a real newline -- the
        # distinction this escaping exists to preserve.
        text = text.replace("\\", "\\\\")
        # Quoting does not contain a newline: it still ends the physical line,
        # and the rest parses as a record of its own, which is how a
        # caller-supplied value forges log entries (CWE-117). So control
        # characters are rewritten, not merely wrapped in quotes.
        text = "".join(
            c if c.isprintable() or c == "\t" else _CONTROL_ESCAPES.get(c, _REPLACEMENT)
            for c in text
        )
        if text == "" or any(c in text for c in ' "=\t'):
            text = '"' + text.replace('"', '\\"') + '"'
        out.append(f"{key}={text}")
    return " ".join(out)


def _bounded(value: str, limit: int = 120) -> str:
    """Truncate a caller-supplied value to a length fit for one log line.

    Starlette caps a form field at 1MiB, so a malformed `page_ranges` could
    put a megabyte on one line and, repeated, flood the log that the rest of
    this module exists to keep readable. `%r` already neutralizes its
    contents; this bounds its size.
    """
    if len(value) <= limit:
        return value
    return value[:limit] + f"...({len(value)} chars)"


def _safe_log_name(raw: str | None, limit: int = 120) -> str:
    """Reduce an uploaded filename to one printable token safe to log.

    `os.path.basename` strips directories but not control characters. A
    filename holding a newline forges whole lines in this module's log format,
    and an ANSI escape runs when an operator views the log, so a log meant to
    settle what happened could instead be written by the caller.
    """
    name = os.path.basename(raw or "unnamed")
    name = "".join(c if c.isprintable() else _REPLACEMENT for c in name)
    if len(name) > limit:
        name = name[:limit] + "...(truncated)"
    return name or "unnamed"


def _stages_slowest_first(step_timings: dict[str, Any]) -> dict[str, str]:
    """Per-stage durations for the completion line, slowest first.

    #414 was a request whose cost was almost entirely OCR, reported in a fixed
    order that put layout ahead of it, so the number that explained the
    request was not the one the eye landed on.
    """
    # Guarded on the value, not just the key: `extract_timings` builds these
    # from docling's ProfilingItem, and a stage that reported nothing usable
    # would otherwise reach the format string as None and cost the request its
    # response over a log line.
    usable = {
        name: item["total_s"]
        for name, item in step_timings.items()
        if name in _STAGE_LABELS
        and isinstance(item, dict)
        and isinstance(item.get("total_s"), (int, float))
    }
    return {
        _STAGE_LABELS[name]: f"{total:.1f}s"
        for name, total in sorted(
            usable.items(), key=lambda kv: kv[1], reverse=True
        )
    }


def _converted_page_count(
    page_range: tuple[int, int] | None, total_pages: int | None
) -> int | None:
    """How many pages a request actually converted.

    docling reports the document's length, which is the answer only when the
    whole document was asked for. Returns None when neither bound is known.
    """
    if page_range is None:
        return total_pages
    start, end = page_range
    if total_pages is not None:
        end = min(end, total_pages)
        start = max(start, 1)
    return max(0, end - start + 1)


def _client_address(request: Any) -> str:
    """Who sent this request, for the log.

    The server binds 0.0.0.0 by default and has no authentication, so the
    caller's address is the only thing tying an upload to an origin. uvicorn's
    access log used to carry it; this server logs its own request lines
    instead, which left nothing recording the sender.
    """
    client = getattr(request, "client", None)
    if client is None or not getattr(client, "host", None):
        # Absent for a connection over a Unix socket, and in tests that build
        # a request without one.
        return "unknown"
    return client.host


def _probe_page_count(pdf_path: str) -> int | None:
    """Page count of an uploaded PDF, or None if it cannot be read.

    Uses pypdfium2, which docling already depends on. Failure is not an error
    here: a PDF too damaged to page-count may still convert, and the count is
    only used to annotate log lines.
    """
    try:
        import pypdfium2

        doc = pypdfium2.PdfDocument(pdf_path)
        try:
            return len(doc)
        finally:
            doc.close()
    except Exception as e:
        logger.debug("could not read page count from the upload: %s", e)
        return None


class _ConversionHeartbeat:
    """Report that a long conversion is still running, from a side thread.

    Per-page progress has no seam to read: docling keeps the finished-page
    tally in a local of its pipeline's `execute()`, and its per-stage page
    lines are DEBUG-only, below the level this server runs at. What an operator
    needs first is anyway the difference between "working" and "hung", which
    elapsed time answers honestly; the per-stage breakdown logged at the end
    says where the time actually went.

    Runs as a daemon so it can never hold up interpreter shutdown.
    """

    def __init__(self, file_name: str, page_count: int | None) -> None:
        self._file_name = file_name
        self._page_count = page_count
        self._stop = threading.Event()
        self._thread: threading.Thread | None = None
        # Inherit the request id so heartbeat lines carry the same tag.
        self._request_id = _request_id.get()

    def __enter__(self) -> "_ConversionHeartbeat":
        self._thread = threading.Thread(
            target=self._run, name="convert-heartbeat", daemon=True
        )
        self._thread.start()
        return self

    def __exit__(self, *exc: Any) -> None:
        self._stop.set()
        if self._thread is not None:
            self._thread.join(timeout=1.0)

    @staticmethod
    def _interval_at(elapsed: float) -> float:
        """Heartbeat spacing for a conversion that has run this long.

        A caller that shortens `_PROGRESS_INTERVAL_S` below the table's first
        step -- the tests, to avoid waiting out a real backoff -- gets that
        value at every stage instead.
        """
        if _PROGRESS_INTERVAL_S < _PROGRESS_BACKOFF[0][1]:
            return _PROGRESS_INTERVAL_S
        for until, interval in _PROGRESS_BACKOFF:
            if until is None or elapsed < until:
                return interval
        return _PROGRESS_BACKOFF[-1][1]

    def _run(self) -> None:
        token = _request_id.set(self._request_id)
        try:
            start = time.perf_counter()
            while not self._stop.wait(
                self._interval_at(time.perf_counter() - start)
            ):
                logger.info(
                    "converting %s",
                    _pairs(
                        file=self._file_name,
                        pages=self._page_count,
                        elapsed=f"{time.perf_counter() - start:.0f}s",
                    ),
                )
        finally:
            _request_id.reset(token)


def build_conversion_response(
    status_value: str,
    json_content: dict,
    processing_time: float,
    errors: list[str],
    requested_pages: tuple[int, int] | None,
    total_pages: int | None = None,
    timings: dict[str, Any] | None = None,
) -> dict:
    """Build a structured conversion response with status and failed page info.

    When Docling encounters errors (e.g., std::bad_alloc in PDF preprocessing),
    it may still include failed pages as empty entries in the pages dict.
    This function combines two strategies to detect failed pages:
    1. Parse page numbers from error messages ("Page N: <error>")
    2. Detect pages missing from the output pages dict (gap detection)
    Both results are merged (union) since each catches a different failure mode.

    Args:
        status_value: Docling ConversionStatus value as string (e.g., "success", "partial_success").
        json_content: The exported document dict from Docling.
        processing_time: Time taken for conversion in seconds.
        errors: List of error message strings from Docling.
        requested_pages: Tuple of (start, end) 1-indexed page range, or None for all pages.
        total_pages: Total page count of the input document (from Docling InputDocument).
                     Used to detect boundary page failures when requested_pages is None.

    Returns:
        Response dict with status, document, errors, failed_pages, and processing_time.
    """
    failed_pages: list[int] = []

    if status_value == "partial_success":
        # Strategy 1: Extract failed pages from error messages (reliable —
        # docling may include failed pages as empty entries in the pages dict,
        # making gap detection ineffective)
        error_failed = set(_extract_failed_pages_from_errors(errors))

        # Strategy 2: Detect pages missing from the pages dict (catches
        # failures that don't produce "Page N:" error messages)
        gap_failed: set[int] = set()
        pages_dict = json_content.get("pages", {})
        present_pages = set()
        for k in pages_dict.keys():
            try:
                present_pages.add(int(k))
            except (ValueError, TypeError):
                # Bounded like the other values this module echoes. docling
                # builds these keys, so an enormous one is a bug rather than
                # an attack, but a log line is capped either way.
                logger.warning(
                    "unexpected_page_key %s",
                    _pairs(key=_bounded(repr(k))),
                )

        if requested_pages:
            expected_pages = set(range(requested_pages[0], requested_pages[1] + 1))
        elif total_pages is not None:
            expected_pages = set(range(1, total_pages + 1))
        elif present_pages:
            logger.warning(
                "No page range or total_pages available; boundary page failures cannot be detected"
            )
            expected_pages = set(range(min(present_pages), max(present_pages) + 1))
        else:
            expected_pages = set()

        gap_failed = expected_pages - present_pages

        # Union: each strategy catches a different failure mode
        failed_pages = sorted(error_failed | gap_failed)

    response: dict[str, Any] = {
        "status": status_value,
        "document": {
            "json_content": json_content,
        },
        "processing_time": processing_time,
        "errors": errors,
        "failed_pages": failed_pages,
    }

    if timings:
        response["timings"] = timings

    return response


def sanitize_unicode(data: Any) -> Any:
    """Recursively replace lone surrogates and null characters with U+FFFD.

    Docling OCR can produce lone surrogates (U+D800-U+DFFF) and null characters
    from PDFs with malformed font encodings. These pass through json.dumps(ensure_ascii=False)
    but fail on .encode('utf-8') in Starlette's JSONResponse.render(), causing
    UnicodeEncodeError and a 500 response.

    This mirrors the Java-side TextProcessor.replaceUndefinedCharacters().

    Args:
        data: Arbitrary data structure (dict, list, str, or primitive) from
              Docling's export_to_dict() output.

    Returns:
        The same structure with problematic characters replaced by U+FFFD.
    """
    if isinstance(data, str):
        return _INVALID_UNICODE_RE.sub("\ufffd", data)
    if isinstance(data, dict):
        return {k: sanitize_unicode(v) for k, v in data.items()}
    if isinstance(data, list):
        return [sanitize_unicode(item) for item in data]
    return data


def _get_loop_setting() -> str:
    """Return the uvicorn event loop setting appropriate for the current platform.

    uvloop is not supported on Windows, so we force 'asyncio' there.
    On other platforms, 'auto' lets uvicorn use uvloop if available.
    """
    if sys.platform == "win32":
        return "asyncio"
    return "auto"


def _check_dependencies():
    """Check if hybrid dependencies are installed."""
    missing = []
    try:
        import uvicorn  # noqa: F401
    except ImportError:
        missing.append("uvicorn")
    try:
        import fastapi  # noqa: F401
    except ImportError:
        missing.append("fastapi")
    try:
        import docling  # noqa: F401
    except ImportError:
        missing.append("docling")

    if missing:
        raise ImportError(
            f"Missing dependencies: {', '.join(missing)}. "
            "Install with: pip install opendataloader-pdf[hybrid]"
        )


def _check_ocr_engine_available(engine_kind: str) -> tuple[bool, str]:
    """Probe runtime prerequisites for the selected OCR engine.

    Called at startup so a missing binary or Python package surfaces before the
    first request rather than mid-conversion. Returns (ok, error_message).

    `easyocr` ships with the `[hybrid]` extra and `auto` defers engine choice to
    docling at conversion time, so both are treated as always available. Other
    engines pull in extra system or Python dependencies that are not declared
    in pyproject and must be installed by the user.
    """
    import importlib.util
    import shutil

    if engine_kind in ("auto", "easyocr"):
        return True, ""

    if engine_kind == "tesseract":
        # docling's TesseractCliOcrOptions shells out to the `tesseract` binary.
        if shutil.which("tesseract") is None:
            return False, (
                "OCR engine 'tesseract' selected but the `tesseract` binary was not "
                "found on PATH. Install Tesseract for your platform "
                "(e.g., `brew install tesseract`, `apt install tesseract-ocr`, "
                "`choco install tesseract`) and ensure the language data files for "
                "your --ocr-lang are installed (e.g., `tesseract-ocr-mal` for Malayalam)."
            )
        return True, ""

    if engine_kind == "tesserocr":
        if importlib.util.find_spec("tesserocr") is None:
            return False, (
                "OCR engine 'tesserocr' selected but the `tesserocr` Python package "
                "is not installed. Install it with `pip install tesserocr` "
                "(libtesseract must also be available at runtime; on Windows install "
                "a wheel that matches your installed Tesseract major version)."
            )
        return True, ""

    if engine_kind == "rapidocr":
        # rapidocr's default backend is ONNX Runtime; docling 2.91 imports
        # `from rapidocr import EngineType, RapidOCR` and routes through it.
        if importlib.util.find_spec("rapidocr") is None:
            return False, (
                "OCR engine 'rapidocr' selected but the `rapidocr` Python package "
                "is not installed. Install it with `pip install rapidocr onnxruntime`."
            )
        if importlib.util.find_spec("onnxruntime") is None:
            return False, (
                "OCR engine 'rapidocr' selected but `onnxruntime` is not installed. "
                "rapidocr's default backend requires it. Install with "
                "`pip install onnxruntime` (or, for GPU, `pip install onnxruntime-gpu`)."
            )
        return True, ""

    if engine_kind == "ocrmac":
        if sys.platform != "darwin":
            return False, (
                "OCR engine 'ocrmac' selected but this is not macOS "
                f"(platform={sys.platform!r}). The ocrmac engine uses Apple's Vision "
                "framework and only runs on macOS."
            )
        if importlib.util.find_spec("ocrmac") is None:
            return False, (
                "OCR engine 'ocrmac' selected but the `ocrmac` Python package "
                "is not installed. Install it with `pip install ocrmac`."
            )
        return True, ""

    if engine_kind == "nemotron-ocr":
        # docling gates this engine behind the `nemotron_ocr` package, published
        # for Linux x86_64 / CUDA only. Without the probe the engine reaches
        # conversion and raises ImportError from inside the pipeline.
        if importlib.util.find_spec("nemotron_ocr") is None:
            return False, (
                "OCR engine 'nemotron-ocr' selected but the `nemotron_ocr` Python "
                "package is not installed. Install it with "
                '`pip install "docling[feat-ocr-nemotron]"` (Linux x86_64 with CUDA; '
                "see docling's documentation for the supported Python and CUDA versions)."
            )
        return True, ""

    # Unknown engine kind — fail closed. argparse `choices` filters the CLI
    # surface, so this branch is reachable via direct programmatic calls or
    # when docling registers a new engine kind we haven't added a probe for.
    # Falling through to True would silently green-light unverified engines
    # and defer the failure to the first conversion request.
    return False, (
        f"OCR engine {engine_kind!r} is not recognized by the availability "
        "probe. Add a probe branch for this engine kind in "
        "`_check_ocr_engine_available()`."
    )


def create_converter(
    force_full_page_ocr: bool = False,
    disable_ocr: bool = False,
    ocr_engine: str = "easyocr",
    psm: int | None = None,
    ocr_lang: list[str] | None = None,
    enrich_formula: bool = False,
    enrich_picture_description: bool = False,
    picture_description_prompt: str | None = None,
    device: str = "auto",
    heading_hierarchy: bool = False,
):
    """Create a DocumentConverter with the specified options.

    Args:
        force_full_page_ocr: If True, force OCR on all pages regardless of text content.
                            If False (default), OCR only where needed.
        disable_ocr: If True, disable OCR entirely (do_ocr=False). Useful when input PDFs
                    already have reliable embedded text — prevents duplicate text extraction
                    from images (charts, diagrams, screenshots). Mutually exclusive with
                    force_full_page_ocr at the CLI level.
        ocr_engine: OCR engine kind to use. Engine availability is delegated to docling's
                    factory (`get_ocr_factory`). Each engine has its own license, language
                    coverage, and accuracy characteristics; this project does not validate
                    engine accuracy. Default: "easyocr" (preserves prior behavior).
        psm: Tesseract Page Segmentation Mode. Only applied when ocr_engine is
             "tesseract" or "tesserocr". Ignored otherwise. Range and semantics
             are owned by Tesseract / docling; see `tesseract --help-extra`.
        ocr_lang: List of OCR language codes. The code system depends on the chosen engine
                  (EasyOCR uses 'ko,en', Tesseract uses 'kor,eng', RapidOCR uses
                  'english,chinese', ocrmac uses 'en-US'). If None, the engine's default
                  languages are used.
        enrich_formula: If True, enable formula enrichment (LaTeX extraction).
        enrich_picture_description: If True, enable picture description (alt text generation).
        picture_description_prompt: Custom prompt forwarded to the VLM. If None or blank/whitespace-only, docling's default prompt is used.
        device: Accelerator device for model inference. Options: "auto", "cpu", "cuda", "mps", "xpu".
                "auto" lets Docling select the best available device. Default: "auto".
        heading_hierarchy: If True, infer section-header depth so subsections nest
                under their parent instead of all landing at level 1.
    """
    from docling.datamodel.accelerator_options import AcceleratorOptions
    from docling.datamodel.base_models import InputFormat
    from docling.datamodel.pipeline_options import (
        AcceleratorOptions,
        HeadingHierarchyOptions,
        PdfPipelineOptions,
        PictureDescriptionVlmOptions,
        TableFormerMode,
        TableStructureOptions,
        TesseractCliOcrOptions,
        TesseractOcrOptions,
    )
    from docling.document_converter import DocumentConverter, PdfFormatOption
    from docling.models.factories import get_ocr_factory

    # Delegate engine selection to docling's factory. We block external plugins for
    # security/reproducibility; the module-level _OCR_ENGINE_DENYLIST filters
    # engines unsuitable for hybrid local mode (e.g., remote inference servers).
    ocr_factory = get_ocr_factory(allow_external_plugins=False)
    if ocr_engine in _OCR_ENGINE_DENYLIST:
        # Programmatic callers (importing this module) bypass argparse `choices`,
        # so enforce the denylist here too. Without this, the module-level claim
        # that `_OCR_ENGINE_DENYLIST` is shared across CLI and create_converter
        # would only be true at the CLI layer.
        available = sorted(set(ocr_factory.registered_kind) - _OCR_ENGINE_DENYLIST)
        raise ValueError(
            f"OCR engine '{ocr_engine}' is not supported in hybrid local mode "
            f"(filtered by _OCR_ENGINE_DENYLIST). Available engines: {available}"
        )
    try:
        ocr_options = ocr_factory.create_options(
            kind=ocr_engine,
            force_full_page_ocr=force_full_page_ocr,
        )
    except RuntimeError as e:
        # Library-friendly error type so programmatic callers can catch and retry
        # with a different engine. main() relies on argparse `choices` to gate
        # invalid CLI input, so this branch is reached only via direct calls.
        available = sorted(set(ocr_factory.registered_kind) - _OCR_ENGINE_DENYLIST)
        raise ValueError(
            f"Unknown ocr_engine '{ocr_engine}': {e}\nAvailable engines: {available}"
        ) from e

    if ocr_lang:
        ocr_options.lang = ocr_lang

    # Tesseract-only: Page Segmentation Mode
    if psm is not None and isinstance(
        ocr_options, (TesseractOcrOptions, TesseractCliOcrOptions)
    ):
        ocr_options.psm = psm

    # Configure picture description options with custom prompt.
    # When picture_description_prompt is None or blank, omit the field so
    # docling's built-in default prompt is used. A blank string would otherwise
    # silently produce empty-prompt output — same class of silent-flag bug
    # as PDFDLOSP-20 reported.
    picture_description_options = None
    if enrich_picture_description:
        vlm_kwargs: dict[str, Any] = {
            "repo_id": "HuggingFaceTB/SmolVLM-256M-Instruct",
        }
        if picture_description_prompt and picture_description_prompt.strip():
            vlm_kwargs["prompt"] = picture_description_prompt
        picture_description_options = PictureDescriptionVlmOptions(**vlm_kwargs)

    pipeline_kwargs = {
        "do_ocr": not disable_ocr,
        "do_table_structure": True,
        "ocr_options": ocr_options,
        "table_structure_options": TableStructureOptions(mode=TableFormerMode.ACCURATE),
        "do_formula_enrichment": enrich_formula,
        "do_picture_description": enrich_picture_description,
        "generate_picture_images": enrich_picture_description,
        "accelerator_options": AcceleratorOptions(device=device),
        # The layout model labels a region SECTION_HEADER without a depth, so
        # every heading the PDF path emits defaults to level 1 and the hierarchy
        # is flat. docling's heading-hierarchy stage infers the depth from the
        # PDF outline, then section numbering, then visual style (#441).
        "heading_hierarchy_options": HeadingHierarchyOptions(
            enabled=heading_hierarchy
        ),
        # The style tier of that stage reads the parsed PDF cells, which are
        # discarded unless this is on — without them docling silently skips style
        # inference and only numbered headings get a depth, leaving Abstract,
        # References and the like at level 1. Gated on the flag because keeping
        # the cells costs memory on every page.
        "generate_parsed_pages": heading_hierarchy,
    }
    if picture_description_options is not None:
        pipeline_kwargs["picture_description_options"] = picture_description_options

    if device != "auto":
        pipeline_kwargs["accelerator_options"] = AcceleratorOptions(device=device)

    pipeline_options = PdfPipelineOptions(**pipeline_kwargs)

    # `format_options` only overrides options for the formats it lists; it does
    # not restrict input. Without `allowed_formats` docling enables every format
    # it knows (31 in 2.124.0, up from 17 in 2.94.0), so an office document
    # uploaded to this PDF-only server is sniffed by content and parsed by that
    # format's backend regardless of the `.pdf` temp-file suffix.
    return DocumentConverter(
        allowed_formats=[InputFormat.PDF],
        format_options={
            InputFormat.PDF: PdfFormatOption(pipeline_options=pipeline_options)
        },
    )


def create_app(
    force_ocr: bool = False,
    disable_ocr: bool = False,
    ocr_engine: str = "easyocr",
    psm: int | None = None,
    ocr_lang: list[str] | None = None,
    enrich_formula: bool = False,
    enrich_picture_description: bool = False,
    picture_description_prompt: str | None = None,
    max_file_size: int = MAX_FILE_SIZE,
    device: str = "auto",
    heading_hierarchy: bool = False,
):
    """Create and configure the FastAPI application.

    Args:
        force_ocr: If True, force full-page OCR on all pages.
        disable_ocr: If True, disable OCR entirely. Mutually exclusive with force_ocr at CLI.
        ocr_engine: OCR engine kind (delegated to docling's get_ocr_factory). Default: "easyocr".
        psm: Tesseract Page Segmentation Mode. Only applied for Tesseract engines.
        ocr_lang: List of OCR language codes (engine-specific format).
        enrich_formula: If True, enable formula enrichment (LaTeX extraction).
        enrich_picture_description: If True, enable picture description (alt text generation).
        picture_description_prompt: Custom prompt forwarded to the VLM. If None or blank/whitespace-only, docling's default prompt is used.
        max_file_size: Maximum file size in bytes. 0 means no limit (default).
        device: Accelerator device for model inference ("auto", "cpu", "cuda", "mps", "xpu").
        heading_hierarchy: If True, infer section-header depth so subsections nest
                under their parent instead of all landing at level 1.
    """
    from fastapi import FastAPI, File, Form, Request, UploadFile
    from fastapi.responses import JSONResponse

    # Profile converters: initialized lazily on first /v1/profile/file request
    profile_converters: dict[str, Any] = {}

    @asynccontextmanager
    async def lifespan(_app: FastAPI):
        """Lifespan context manager for startup and shutdown events."""
        global converter
        lang_str = ",".join(ocr_lang) if ocr_lang else "default"
        enrichments = []
        if enrich_formula:
            enrichments.append("formula")
        if enrich_picture_description:
            enrichments.append("picture-description")
        enrichment_str = ",".join(enrichments) if enrichments else "none"
        logger.info(
            f"Initializing DocumentConverter "
            f"(do_ocr={not disable_ocr}, ocr_engine={ocr_engine}, force_ocr={force_ocr}, "
            f"lang={lang_str}, enrichments={enrichment_str}, device={device}, "
            f"heading_hierarchy={heading_hierarchy})..."
        )
        start = time.perf_counter()

        converter = create_converter(
            force_full_page_ocr=force_ocr,
            disable_ocr=disable_ocr,
            ocr_engine=ocr_engine,
            psm=psm,
            ocr_lang=ocr_lang,
            enrich_formula=enrich_formula,
            enrich_picture_description=enrich_picture_description,
            picture_description_prompt=picture_description_prompt,
            device=device,
            heading_hierarchy=heading_hierarchy,
        )

        elapsed = time.perf_counter() - start
        logger.info("converter_constructed %s", _pairs(dur=f"{elapsed:.2f}s"))

        # Constructing the converter does not load any model: docling builds a
        # pipeline lazily inside the first convert() call. That made the first
        # request absorb the whole model load -- 261s of the 293s reported in
        # #414 -- and report it as document conversion time, so the reporter
        # read it as "CPU inference is slow". Loading here moves the cost to
        # startup, where the log can name it, and leaves the first request as
        # fast as every later one.
        from docling.datamodel.base_models import InputFormat

        warm_start = time.perf_counter()
        logger.info("loading_models %s", _pairs(models="layout,tables,ocr"))
        try:
            converter.initialize_pipeline(InputFormat.PDF)
            logger.info(
                "models_ready %s",
                _pairs(
                    dur=f"{time.perf_counter() - warm_start:.2f}s",
                    state="accepting requests",
                ),
            )
        except Exception as e:
            # A failed warmup must not stop the server: the same load is retried
            # on the first request, and that path reports errors to the client.
            # With the traceback: this is the one report of why warmup failed,
            # and the first request only repeats the failure as a 500.
            logger.warning(
                "warmup_failed %s",
                _pairs(
                    dur=f"{time.perf_counter() - warm_start:.2f}s",
                    error=_bounded(str(e), 500),
                    fallback="load on first request",
                ),
                exc_info=True,
            )
        yield
        # Cleanup on shutdown (if needed)

    app = FastAPI(
        title="Docling Fast Server",
        description="Fast PDF conversion using docling SDK with singleton pattern",
        version="1.0.0",
        lifespan=lifespan,
    )

    @app.get("/health")
    def health():
        """Health check endpoint."""
        return {"status": "ok"}

    @app.post("/v1/convert/file")
    async def convert_file(
        request: Request,
        files: UploadFile = File(...),
        page_ranges: Optional[str] = Form(default=None),
    ):
        """Convert PDF file to JSON (DoclingDocument format).

        Only JSON output is provided - markdown and HTML are generated by
        Java processors for consistent reading order application.

        Args:
            files: The PDF file to convert
            page_ranges: Page range string "start-end" (e.g., "1-5") (optional)

        Returns:
            JSON response with document content.
        """
        global converter

        # Tag every line from here on, including docling's, with one id so
        # concurrent uploads can be told apart in the log.
        _request_id.set(secrets.token_hex(_REQUEST_ID_BYTES))
        request_start = time.perf_counter()
        file_name = _safe_log_name(files.filename)

        if converter is None:
            logger.error(
                "rejected %s",
                _pairs(
                    status=503,
                    reason="server not initialized",
                    # Normally means startup is still loading models, which is
                    # worth waiting out rather than investigating.
                    hint="models may still be loading",
                ),
            )
            return JSONResponse(
                {"status": "failure", "errors": ["Server not initialized"]},
                status_code=503,
            )

        # Parse page_ranges string to tuple
        page_range_tuple = None
        if page_ranges:
            parsed = None
            try:
                parts = page_ranges.split("-")
                if len(parts) == 2:
                    parsed = (int(parts[0]), int(parts[1]))
            except ValueError:
                parsed = None
            if parsed is None:
                # This used to be a bare `pass`: an unparseable range
                # silently converted the whole document, so a caller asking
                # for pages 1-5 got all of them with no way to tell.
                logger.warning(
                    "bad_page_ranges %s",
                    _pairs(
                        value=_bounded(page_ranges),
                        expected="start-end",
                        action="converting whole document",
                    ),
                )
            page_range_tuple = parsed

        # Stream upload to temp file and enforce size incrementally
        tmp_path = None
        total_size = 0
        with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as tmp:
            tmp_path = tmp.name
            while True:
                chunk = await files.read(UPLOAD_CHUNK_SIZE)
                if not chunk:
                    break
                total_size += len(chunk)
                if max_file_size > 0 and total_size > max_file_size:
                    tmp.close()
                    os.unlink(tmp_path)
                    # Logged server-side too: a 413 the client sees leaves no
                    # trace otherwise, so repeated rejections look like silence.
                    logger.warning(
                        "rejected %s",
                        _pairs(
                            status=413,
                            file=file_name,
                            size=f"{total_size / (1024 * 1024):.1f}MB",
                            max=f"{max_file_size / (1024 * 1024):.1f}MB",
                            client=_client_address(request),
                        ),
                    )
                    return JSONResponse(
                        {
                            "status": "failure",
                            "errors": [f"File size exceeds maximum allowed ({max_file_size // (1024*1024)}MB)"],
                        },
                        status_code=413,
                    )
                tmp.write(chunk)

        try:
            # Read the page count up front. docling reports it only on the
            # result, which is too late to say how much work a slow request is
            # doing, or to attribute it if the process dies mid-conversion.
            # Off the event loop: parsing a pathological PDF took 30ms here,
            # which would be 30ms of every other request's latency. Inside the
            # try so the temp file is removed even if the client disconnects
            # while this runs.
            page_count = await asyncio.to_thread(_probe_page_count, tmp_path)
            logger.info(
                "POST /v1/convert/file %s",
                _pairs(
                    file=file_name,
                    size=f"{total_size / (1024 * 1024):.1f}MB",
                    pages=page_count if page_count is not None else "?",
                    range=f"{page_range_tuple[0]}-{page_range_tuple[1]}"
                    if page_range_tuple
                    else "all",
                    client=_client_address(request),
                ),
            )

            def _do_convert():
                # Timed separately so a queued request does not read as a
                # slow one.
                queue_start = time.perf_counter()
                with _convert_lock:
                    waited = time.perf_counter() - queue_start
                    if waited >= 0.1:
                        logger.info(
                            "queued %s",
                            _pairs(
                                waited=f"{waited:.1f}s",
                                reason="one conversion at a time",
                            ),
                        )
                    t0 = time.perf_counter()
                    with _ConversionHeartbeat(file_name, page_count):
                        if page_range_tuple:
                            res = converter.convert(
                                tmp_path, page_range=page_range_tuple
                            )
                        else:
                            res = converter.convert(tmp_path)
                    return res, time.perf_counter() - t0

            result, processing_time = await asyncio.to_thread(_do_convert)

            # Export to JSON (DoclingDocument format)
            json_content = result.document.export_to_dict()

            # Sanitize lone surrogates and null chars from OCR output to prevent
            # UnicodeEncodeError in Starlette's JSONResponse.render()
            json_content = sanitize_unicode(json_content)

            # Extract status and errors from Docling ConversionResult
            from docling.datamodel.base_models import ConversionStatus

            status_value = result.status.value if hasattr(result.status, "value") else str(result.status)
            errors = [getattr(e, "error_message", str(e)) for e in result.errors] if result.errors else []

            # Get total page count for accurate failed-page detection
            input_page_count = getattr(result.input, "page_count", None) if result.input else None

            if result.status == ConversionStatus.PARTIAL_SUCCESS:
                logger.warning(
                    "partial_success %s",
                    _pairs(errors=len(errors), detail="see failed_pages in response"),
                )

            # Extract per-step pipeline timings (layout, ocr, table_structure, etc.)
            step_timings = extract_timings(result)

            response = build_conversion_response(
                status_value=status_value,
                json_content=json_content,
                processing_time=processing_time,
                errors=errors,
                requested_pages=page_range_tuple,
                total_pages=input_page_count,
                timings=step_timings,
            )

            # The per-stage breakdown already travelled in the response body,
            # where only an API caller could see it. Logging it as well is what
            # turns "slow" into "slow in OCR" without a re-run.
            stages = _stages_slowest_first(step_timings)
            # Count what was converted, not what the file holds: on a page
            # range the two differ, and dividing by the document's length
            # understated the per-page cost -- a 3-page range out of 14 pages
            # reported 0.34s/pg for work that cost 1.60s/pg.
            converted_page_count = _converted_page_count(
                page_range_tuple, input_page_count
            )
            request_elapsed = time.perf_counter() - request_start
            logger.info(
                "done %s",
                _pairs(
                    status="ok" if status_value == "success" else status_value,
                    dur=f"{processing_time:.1f}s",
                    per_page=f"{processing_time / converted_page_count:.2f}s"
                    if converted_page_count
                    else None,
                    pages=converted_page_count
                    if converted_page_count is not None
                    else "?",
                    # Suppressed when it would merely restate dur. A gap means
                    # time went somewhere outside convert() -- the upload, the
                    # page probe, the queue, the JSON export -- and which one
                    # is the next thing to find out.
                    total=f"{request_elapsed:.1f}s"
                    if (request_elapsed - processing_time) > 1.0
                    else None,
                    **stages,
                ),
            )

            return JSONResponse(response)

        except Exception as e:
            logger.error(
                "failed %s",
                _pairs(
                    status=500,
                    dur=f"{time.perf_counter() - request_start:.1f}s",
                    file=file_name,
                    size=f"{total_size / (1024 * 1024):.1f}MB",
                    # Bounded like every other caller-influenced value: a
                    # parser error can carry offsets and object data from the
                    # uploaded file, and there is no cap on its length.
                    error=_bounded(str(e), 500),
                ),
                # Let logging frame the traceback rather than splicing it into
                # the message, so the logfmt line stays one line.
                exc_info=True,
            )
            return JSONResponse(
                {
                    "status": "failure",
                    "errors": ["PDF conversion failed. Check server logs for details."],
                },
                status_code=500,
            )
        finally:
            if tmp_path and os.path.exists(tmp_path):
                os.unlink(tmp_path)

    def _ensure_profile_converters():
        """Lazily initialize profile converters on first use."""
        if profile_converters:
            return
        profiles = {
            "base": dict(enrich_formula=False, enrich_picture_description=False),
            "picture": dict(enrich_formula=False, enrich_picture_description=True),
            "formula": dict(enrich_formula=True, enrich_picture_description=False),
        }
        for name, opts in profiles.items():
            logger.info(f"Initializing profile converter: {name} ({opts})")
            t0 = time.perf_counter()
            profile_converters[name] = create_converter(
                force_full_page_ocr=force_ocr,
                disable_ocr=disable_ocr,
                ocr_engine=ocr_engine,
                psm=psm,
                ocr_lang=ocr_lang,
                picture_description_prompt=picture_description_prompt,
                device=device,
                heading_hierarchy=heading_hierarchy,
                **opts,
            )
            logger.info(f"  {name} initialized in {time.perf_counter() - t0:.2f}s")

    @app.post("/v1/profile/file")
    async def profile_file(
        files: UploadFile = File(...),
    ):
        """Run the same PDF through base / +picture / +picture+formula converters.

        Returns per-profile timings for cost comparison.
        """
        _ensure_profile_converters()

        # Stream upload to temp file
        tmp_path = None
        with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as tmp:
            tmp_path = tmp.name
            while True:
                chunk = await files.read(UPLOAD_CHUNK_SIZE)
                if not chunk:
                    break
                tmp.write(chunk)

        try:
            results = {}
            for profile_name, conv in profile_converters.items():
                def _run(c=conv):
                    with _convert_lock:
                        t0 = time.perf_counter()
                        res = c.convert(tmp_path)
                        return res, time.perf_counter() - t0

                result, wall_time = await asyncio.to_thread(_run)
                timings = extract_timings(result)

                # Count pictures and formulas
                json_content = result.document.export_to_dict()
                pictures = json_content.get("pictures", [])
                pics_total = len(pictures)
                pics_described = sum(
                    1 for p in pictures
                    if p.get("captions") or p.get("annotations")
                )
                texts = json_content.get("texts", [])
                formulas_total = sum(1 for t in texts if t.get("label") == "formula")
                tables_total = len(json_content.get("tables", []))

                results[profile_name] = {
                    "wall_time_s": round(wall_time, 3),
                    "timings": timings,
                    "pictures": {
                        "total": pics_total,
                        "with_description": pics_described,
                    },
                    "formulas": formulas_total,
                    "tables": tables_total,
                }

            return JSONResponse({"status": "success", "profiles": results})

        except Exception as e:
            logger.error(
                "profile_failed %s",
                _pairs(error=_bounded(str(e), 500)),
                exc_info=True,
            )
            return JSONResponse(
                {"status": "failure", "errors": ["Internal server error"]},
                status_code=500,
            )
        finally:
            if tmp_path and os.path.exists(tmp_path):
                os.unlink(tmp_path)

    return app


def main():
    """Run the server."""
    _check_dependencies()
    import uvicorn

    parser = argparse.ArgumentParser(description="Docling Fast Server for opendataloader-pdf")
    parser.add_argument(
        "--host",
        default=DEFAULT_HOST,
        help=f"Host to bind to (default: {DEFAULT_HOST})",
    )
    parser.add_argument(
        "--port",
        type=int,
        default=DEFAULT_PORT,
        help=f"Port to bind to (default: {DEFAULT_PORT})",
    )
    parser.add_argument(
        "--log-level",
        default="info",
        choices=["debug", "info", "warning", "error"],
        help="Log level (default: info)",
    )
    # OCR mode: --force-ocr and --no-ocr are mutually exclusive (opposite intents)
    ocr_mode_group = parser.add_mutually_exclusive_group()
    ocr_mode_group.add_argument(
        "--force-ocr",
        action="store_true",
        help="Force full-page OCR on all pages, even pages with embedded text. "
             "Use for scanned PDFs where embedded text is unreliable. "
             "Mutually exclusive with --no-ocr.",
    )
    ocr_mode_group.add_argument(
        "--no-ocr",
        action="store_true",
        # ASCII only: argparse --help crashes with UnicodeEncodeError on
        # non-UTF-8 consoles (e.g. cp949 on Korean Windows) if help text
        # contains characters the locale codec cannot encode.
        help="Disable OCR entirely. Use when input PDFs already have reliable embedded text - "
             "prevents duplicate text extraction from images (charts, diagrams, screenshots). "
             "Mutually exclusive with --force-ocr.",
    )

    # Engine selection — delegated to docling's factory.
    # Choices are computed at parse time; the module-level _OCR_ENGINE_DENYLIST
    # filters engines unsuitable for hybrid local mode (single source of truth
    # shared with create_converter and tests).
    try:
        from docling.models.factories import get_ocr_factory as _get_ocr_factory
        _ocr_engine_choices = sorted(
            set(_get_ocr_factory(allow_external_plugins=False).registered_kind)
            - _OCR_ENGINE_DENYLIST
        )
    except ImportError:
        _ocr_engine_choices = ["easyocr"]
    parser.add_argument(
        "--ocr-engine",
        type=str,
        default="easyocr",
        choices=_ocr_engine_choices,
        help=f"OCR engine. Available: {', '.join(_ocr_engine_choices)}. "
             "Use 'auto' for engine auto-selection per page (delegates the choice to docling). "
             "Each engine has its own license, language coverage, and accuracy characteristics; "
             "this server does not validate engine accuracy. "
             "Default: easyocr (preserves prior behavior).",
    )
    parser.add_argument(
        "--psm",
        type=int,
        default=None,
        help="Tesseract Page Segmentation Mode. Applied only when --ocr-engine is "
             "'tesseract' or 'tesserocr'; ignored for other engines. See "
             "`tesseract --help-extra` for valid values.",
    )
    parser.add_argument(
        "--ocr-lang",
        type=str,
        default=None,
        help="OCR languages (comma-separated). Code system depends on --ocr-engine: "
             "EasyOCR uses ISO 639-1 ('ko,en'), Tesseract uses ISO 639-2 ('kor,eng'), "
             "RapidOCR uses 'english,chinese', ocrmac uses BCP-47 ('en-US'). "
             "If omitted, the engine's default languages are used.",
    )
    parser.add_argument(
        "--enrich-formula",
        action="store_true",
        default=False,
        help="Enable formula enrichment model (LaTeX extraction)",
    )
    parser.add_argument(
        "--no-enrich-formula",
        action="store_false",
        dest="enrich_formula",
    )
    parser.add_argument(
        "--enrich-picture-description",
        action="store_true",
        default=False,
        help="Enable picture description model (alt text generation using SmolVLM)",
    )
    parser.add_argument(
        "--no-enrich-picture-description",
        action="store_false",
        dest="enrich_picture_description",
    )
    parser.add_argument(
        "--picture-description-prompt",
        type=str,
        default=None,
        help="Custom prompt for picture description. If unset or blank/whitespace-only, uses docling's default prompt.",
    )
    parser.add_argument(
        "--max-file-size",
        type=_non_negative_int,
        default=MAX_FILE_SIZE,
        help="Maximum upload file size in MB. 0 means no limit (default: 0).",
    )
    parser.add_argument(
        "--device",
        type=str,
        default="auto",
        choices=["auto", "cpu", "cuda", "mps", "xpu"],
        help="Accelerator device for model inference: auto (default), cpu, cuda, mps (Apple Silicon), xpu (Intel GPU).",
    )
    parser.add_argument(
        "--heading-hierarchy",
        action="store_true",
        default=False,
        help="Infer section-header levels so subsections nest under their parent "
             "(1. -> 1.1 -> 1.1.1) instead of every heading coming back as level 1. "
             "Read from the PDF outline first, then section numbering, then visual style.",
    )
    parser.add_argument(
        "--no-heading-hierarchy",
        action="store_false",
        dest="heading_hierarchy",
    )
    args = parser.parse_args()

    configure_logging(args.log_level)

    # Parse ocr_lang
    ocr_lang = None
    if args.ocr_lang:
        ocr_lang = [lang.strip() for lang in args.ocr_lang.split(",") if lang.strip()]

    # Warn when --no-ocr makes other OCR flags inert. We let it through (rather
    # than failing) because the combination is unambiguous — OCR is off — but
    # silently dropping user-supplied flags is unfriendly.
    if args.no_ocr:
        # argparse cannot distinguish explicit `--ocr-engine easyocr` from the
        # implicit default; peek at argv so an explicitly-typed default value
        # is still treated as a user-supplied (inert) flag and reported.
        argv = sys.argv[1:]
        ocr_engine_explicit = any(
            t == "--ocr-engine" or t.startswith("--ocr-engine=") for t in argv
        )
        ignored = []
        if ocr_engine_explicit:
            ignored.append(f"--ocr-engine {args.ocr_engine}")
        if ocr_lang:
            ignored.append(f"--ocr-lang {args.ocr_lang}")
        if args.psm is not None:
            ignored.append(f"--psm {args.psm}")
        if ignored:
            logger.warning(
                "inert_flags %s",
                _pairs(reason="--no-ocr", flags="; ".join(ignored)),
            )

    # Probe engine availability at startup (only when OCR is on). A missing
    # `tesseract` binary or Python package surfaces here as a clear, actionable
    # error rather than as a deferred runtime exception during the first request.
    if not args.no_ocr:
        ok, err = _check_ocr_engine_available(args.ocr_engine)
        if not ok:
            logger.error(err)
            sys.exit(2)

    enrichments = []
    if args.enrich_formula:
        enrichments.append("formula")
    if args.enrich_picture_description:
        enrichments.append("picture-description")

    try:
        import torch
        if torch.cuda.is_available():
            detected = _pairs(
                accelerator="cuda",
                gpu=torch.cuda.get_device_name(0),
                cuda=torch.version.cuda,
            )
        elif hasattr(torch.backends, "mps") and torch.backends.mps.is_available():
            detected = _pairs(accelerator="mps", gpu="Apple Silicon")
        elif hasattr(torch, "xpu") and torch.xpu.is_available():
            detected = _pairs(accelerator="xpu", gpu="Intel GPU")
        else:
            detected = _pairs(accelerator="cpu", gpu="none detected")
    except ImportError:
        detected = _pairs(accelerator="cpu", gpu="torch not installed")
    logger.info("hardware %s", detected)

    # Convert MB to bytes (0 stays 0 = unlimited)
    max_file_size_bytes = args.max_file_size * 1024 * 1024 if args.max_file_size > 0 else 0

    logger.info(
        "starting %s",
        _pairs(
            url=f"http://{args.host}:{args.port}",
            device=args.device,
            log_level=args.log_level,
        ),
    )
    logger.info(
        "config %s",
        _pairs(
            ocr=not args.no_ocr,
            ocr_engine=args.ocr_engine if not args.no_ocr else None,
            force_ocr=args.force_ocr or None,
            ocr_lang=",".join(ocr_lang) if ocr_lang else None,
            psm=args.psm,
            max_file_size=f"{args.max_file_size}MB"
            if max_file_size_bytes > 0
            else "unlimited",
            enrichments=",".join(enrichments) if enrichments else None,
        ),
    )

    app = create_app(
        force_ocr=args.force_ocr,
        disable_ocr=args.no_ocr,
        ocr_engine=args.ocr_engine,
        psm=args.psm,
        ocr_lang=ocr_lang,
        enrich_formula=args.enrich_formula,
        enrich_picture_description=args.enrich_picture_description,
        picture_description_prompt=args.picture_description_prompt,
        max_file_size=max_file_size_bytes,
        device=args.device,
        heading_hierarchy=args.heading_hierarchy,
    )
    uvicorn.run(
        app,
        host=args.host,
        port=args.port,
        # `log_config=None` keeps uvicorn from replacing the dictConfig above
        # with its own timestamp-less format. Its level is set there instead.
        log_config=None,
        loop=_get_loop_setting(),
    )


if __name__ == "__main__":
    main()
