[project]
name = "opendataloader-pdf"
authors = [
  { name="Hancom Inc.", email="opendataloader@hancom.com" },
]
description = "A Python wrapper for OpenDataLoader PDF processing, with bundled Java runtime."
readme = "README.md"
requires-python = ">=3.8"
dynamic = ["version"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)",
    "Operating System :: OS Independent",
]
keywords = ["pdf", "opendataloader", "java", "wrapper", "ai"]

dependencies = [
    "JPype1>=1.4.0",
]

[project.urls]
"Homepage" = "https://github.com/hancom-open-dataloader/opendataloader-pdf"
"Bug Tracker" = "https://github.com/hancom-open-dataloader/opendataloader-pdf/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/opendataloader_pdf"]

[tool.hatch.build.hooks.custom]
path = "build_hook.py"

[tool.hatch.version]
scheme = "from-file"
path = "VERSION"
pattern = "^(?P<version>.+)$"

[tool.hatch.metadata.hooks.custom]
path = "metadata_hook.py"
