[tool.hatch.workspaces.default]
# Tells Hatch which sub-directories are managed packages.
packages = ["packages/opendataloader_pdf"]

# --- Development Environment Configuration ---
[tool.hatch.envs.default]
# Defines the default environment, activated with "hatch shell".
dependencies = [
    "pytest",
    "ruff",
]

[tool.hatch.envs.default.scripts]
# Define convenient shortcuts for common tasks.
# Usage: "hatch run <script_name>", e.g., "hatch run test"

# Run tests
test = "pytest packages/opendataloader_pdf/tests"

# Check for linting errors
lint = "ruff check packages/opendataloader_pdf/src"

# Automatically fix linting errors
"lint:fix" = "ruff check packages/opendataloader_pdf/src --fix"

# Format code
format = "ruff format packages/opendataloader_pdf/src"
