package com.duallab.layout.json.serializers;

public class JsonName {
    public static final String PAGE_NUMBER = "page number";
    public static final String BOUNDING_BOX = "bounding box";
    public static final String TYPE = "type";
    public static final String ID = "id";
    public static final String IMAGE_CHUNK_TYPE = "image";
    public static final String LIST_ITEM_TYPE = "list item";
    public static final String LINE_CHUNK_TYPE = "line";
    public static final String CONTENT = "content";
    public static final String TEXT_CHUNK_TYPE = "text chunk";
    public static final String TABLE_TYPE = "table";
    public static final String LIST_TYPE = "list";
    public static final String TABLE_CELL_TYPE = "table cell";
    public static final String ROW_TYPE = "table row";
    public static final String FONT_TYPE = "font";
    public static final String FONT_SIZE = "font size";
    public static final String TEXT_COLOR = "text color";
    public static final String PARAGRAPH_TYPE = "paragraph";
    public static final String HEADING_TYPE = "heading";
    public static final String KIDS = "kids";
    public static final String LIST_ITEMS = "list items";
    public static final String NUMBER_OF_LIST_ITEMS = "number of list items";
    public static final String PREVIOUS_LIST_ID = "previous list id";
    public static final String NEXT_LIST_ID = "next list id";
    public static final String AUTHOR = "author";
    public static final String TITLE = "title";
    public static final String COLUMN_NUMBER = "column number";
    public static final String ROW_NUMBER = "row number";
    public static final String COLUMN_SPAN = "column span";
    public static final String ROW_SPAN = "row span";
    public static final String NUMBER_OF_ROWS = "number of rows";
    public static final String NUMBER_OF_COLUMNS = "number of columns";
    public static final String NUMBER_OF_PAGES = "number of pages";
    public static final String FILE_NAME = "file name";
    public static final String HEADING_LEVEL = "heading level";
    public static final String CREATION_DATE = "creation date";
    public static final String MODIFICATION_DATE = "modification date";
    public static final String ROWS = "rows";
    public static final String CELLS = "cells";
    public static final String NUMBERING_STYLE = "numbering style";
}
